# Generated by Django 5.0.6 on 2024-06-02 14:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja pozarządowa', 'Organizacja pozarządowa'), ('zbiórka lokalna', 'Zbiórka lokalna')], default='fundacja', max_length=50, verbose_name='Typ')),
                ('categories', models.ManyToManyField(to='donations.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Instytucja',
                'verbose_name_plural': 'Instytucje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość worków')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu')),
                ('city', models.CharField(max_length=255, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Czas odbioru')),
                ('pick_up_comment', models.TextField(blank=True, null=True, verbose_name='Komentarz do odbioru')),
                ('categories', models.ManyToManyField(to='donations.category', verbose_name='Kategorie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.institution', verbose_name='Instytucja')),
            ],
            options={
                'verbose_name': 'Darowizna',
                'verbose_name_plural': 'Darowizny',
                'ordering': ['pick_up_date', 'pick_up_time'],
            },
        ),
    ]
