# Generated by Django 5.0.6 on 2024-06-08 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Podaj prawidłowy numer telefonu w formacie: '+999999999'. Do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu'),
        ),
    ]
