# Generated by Django 5.0.6 on 2024-06-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donation_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='donation',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_donations', to=settings.AUTH_USER_MODEL, verbose_name='Kurier'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken_by_admin',
            field=models.BooleanField(default=False, verbose_name='Zabrany przez admina'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken_by_user',
            field=models.BooleanField(default=False, verbose_name='Zabrany przez użytkownika'),
        ),
    ]
