# Generated by Django 5.0.6 on 2024-06-09 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donation_status_donation_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'Token weryfikacji email', 'verbose_name_plural': 'Tokeny weryfikacji email'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Token resetowania hasła', 'verbose_name_plural': 'Tokeny resetowania hasła'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.institution', verbose_name='Instytucja'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_taken_by_courier',
            field=models.BooleanField(default=False, verbose_name='Zabrane przez kuriera'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_taken_by_user',
            field=models.BooleanField(default=False, verbose_name='Zabrane przez użytkownika'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Komentarz do odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(verbose_name='Czas odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
