# Generated by Django 5.0.6 on 2024-06-09 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_alter_emailverificationtoken_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('bug', 'Błąd'), ('feature', 'Prośba o funkcję'), ('usability', 'Użyteczność'), ('performance', 'Wydajność'), ('security', 'Bezpieczeństwo'), ('other', 'Inne')], max_length=20, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('browser_info', models.CharField(blank=True, max_length=255, verbose_name='Informacje o przeglądarce')),
                ('operating_system', models.CharField(blank=True, max_length=255, verbose_name='System operacyjny')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='Kroki do odtworzenia')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='problem_reports/', verbose_name='Zrzut ekranu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Zgłoszenie problemu',
                'verbose_name_plural': 'Zgłoszenia problemów',
                'ordering': ['-created_at'],
            },
        ),
    ]
